font_family JetBrainsMono Nerd Font

font_size 11

enable_audio_bell no

shell 		  zsh
shell_integration disable

cursor_shape block
cursor_blink_interval 0

url_style curly
disable_ligatures always
remember_window_size no


window_padding_width 	20

scrollbar_handle_opacity 	0
scrollbar_track_opacity 	0
scrollbar_track_hover_opacity 	0

confirm_os_window_close 0


sync_to_monitor no

copy_on_select clipboard

copy_on_select yes

# Special Colors
foreground            #cdd6f4
background            #0f1117
cursor                #f5e0dc
selection_foreground  #0f1117
selection_background  #9399b2

# Standard Colors
color0  #1e1e2e
color8  #45475a

# Red (Deeper, more "Rose Pine")
color1  #f38ba8
color9  #f38ba8

# Green (Emerald/Cyan lean)
color2  #a6e3a1
color10 #a6e3a1

# Yellow/Orange
color3  #f9e2af
color11 #f9e2af

# Blue (Arch Blue)
color4  #89b4fa
color12 #89b4fa

# Magenta/Purple
color5  #cba6f7
color13 #cba6f7

# Cyan
color6  #94e2d5
color14 #94e2d5

# White
color7  #bac2de
color15 #a6adc8

# Window Blur/Transparency (Optional but recommended for Hyprland)
background_opacity 0.62
#map
clear_all_shortcuts yes
map ctrl+i send_text all \x1b[105;5u
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+equal  change_font_size all +2.0
map ctrl+minus  change_font_size all -2.0
map ctrl+shift+e kitten hints --type url
map ctrl+shift+h show_scrollback
scrollback_pager nvim -c 'set ft=man' -
map ctrl+shift+l>f kitten hints --type path --program @
map ctrl+shift+l>u kitten hints --type url
map ctrl+shift+l>l kitten hints --type line --program @
map ctrl+shift+l>w kitten hints --type word --program @
