[[mgr.prepend_keymap]]
on   = "<C-n>" # Feel free to change this to your preferred shortcut
run  = 'shell -- dragon-drop -x -i -T "$@"'
desc = "Drag and drop selected files with Dragon"

[[mgr.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]
desc = "Yank and copy to Wayland clipboard"

[[mgr.prepend_keymap]]
on   = [ "i" ]
run  = "plugin easyjump"
desc = "easyjump"

[[mgr.prepend_keymap]]
on = "Z"
run = "plugin zoxide"
desc = "Jump to a directory via zoxide" 
