
[flavor]
dark = "kanagawa"

[manager]
hovered = { fg = "black", bg = "#ffb6c1", bold = true }

marker_selected = { fg = "#ffb6c1", bg = "#ffb6c1" }

marker_copied   = { fg = "lightyellow", bg = "lightyellow" }
marker_cut      = { fg = "lightred", bg = "lightred" }

